require "rubygems"
require "bundler"
Bundler.setup

desc "Runs preview"
task :preview do
  system "staticmatic preview ."
end

desc "Builds the site"
task :build => 'styles:clear' do
  system "staticmatic build ."
end

desc "Clears and generates new styles, builds and deploys"
task :copy => :build do
  include FileUtils
  
  cp 'site/index.html', '..'
  cp 'site/stylesheets/site.css', '../stylesheets'
  cp 'site/stylesheets/ie.css', '../stylesheets'
  cp 'site/stylesheets/print.css', '../stylesheets'
end

namespace :styles do
  desc "Clears the styles"
  task :clear do
    puts "*** Clearing styles ***"
    system "rm -Rfv site/stylesheets/*"
  end
  
  desc "Generates new styles"
  task :generate => :clear do
    puts "*** Generating styles ***"
    system "compass compile"
  end
end